---

- hosts: all
  become: yes
  vars:
    username: sonar
    password: sonar
    sonar_version: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.5.zip
    pg_version: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    db_name: sonar
  roles: 
   - prerequisites
   - postgres
   - sonar
