---

- name : "Install Prerequisites" 
  yum: 
    state: present
    pkg:   "{{ item }}"
  with_items:
      - java
      - epel-release
      - git
      - wget
      - zip
      - unzip
      - dos2unix
      
#- name: "Install Python"
#  get_url:
#    url: https://bootstrap.pypa.io/get-pip.py
#    dest: /tmp/get-pip.py
#    owner: root
#    group: root
#    mode: 0777
 
#- name: Install PIP
#  command: python get-pip.py chdir = /tmp/
