---

- name: "Install repository package"
  yum: 
    state: present
    pkg: "{{ pg_version }}"
    validate_certs: no

- name: "Install Postgres Package"
  yum: 
    state: present
    pkg: "{{ item }}"
  with_items:
      - postgresql96-server 
      - postgresql96-contrib 
      - postgresql-libs
  register: installed

- name: Initial DB
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: installed.changed
  ignore_errors: True

- name: Copying config file
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  when: installed.changed

- name: Enabling the Service
  systemd:
    name: postgresql-9.6
    enabled: yes

- name: Starting the Service
  systemd:
    name: postgresql-9.6
    state: restarted

- name: Ensure database is created
  become_user: postgres
  become: yes
  postgresql_db: name="{{ db_name }}"
                     
- name: DB User create  
  become_user: postgres
  become: yes
  postgresql_user: 
    db: "{{ db_name }}"
    name: "{{ username }}"
    password: "{{ password }}"
    priv: ALL
    state: present
    encrypted: no
  when: installed.changed

- name: Converting unix file
  command: dos2unix /var/lib/pgsql/9.6/data/pg_hba.conf